### ISSUE TITLE
[URGENT] Update SDWebImage dependency for Apple Privacy

### ISSUE THREAD

**Issue by JoeSzymanskiFAN** [SDWebImage/SDWebImageSwiftUI#310] opened 2024-03-28 17:25 UTC
There is a deadline coming up where Apple requires all usage of SDWebImage to include xcprivacy files. That was added in the 5.18.7 release: https://github.com/SDWebImage/SDWebImage/releases/tag/5.18.7

However, SDWebImageSwiftUI has no way to use the new version, so it's not currently possible to get the required version.

Apple will stop accepting uploads without this file starting on May 1, 2024, so this update needs to be made very soon to allow time to integrate and test the dependency update.

**Comment by dreampiggy** [comment] 2024-03-29 02:06
> SDWebImageSwiftUI has no way to use the new version, so it's not currently possible to get the required version

Why ? See our demo's Podfile.lock


```
PODS:
  - libavif/core (0.11.1)
  - libavif/libdav1d (0.11.1):
    - libavif/core
    - libdav1d (>= 0.6.0)
  - libdav1d (1.2.0)
  - libwebp (1.3.2):
    - libwebp/demux (= 1.3.2)
    - libwebp/mux (= 1.3.2)
    - libwebp/sharpyuv (= 1.3.2)
    - libwebp/webp (= 1.3.2)
  - libwebp/demux (1.3.2):
    - libwebp/webp
  - libwebp/mux (1.3.2):
    - libwebp/demux
  - libwebp/sharpyuv (1.3.2)
  - libwebp/webp (1.3.2):
    - libwebp/sharpyuv
  - SDWebImage (5.19.0):
    - SDWebImage/Core (= 5.19.0)
  - SDWebImage/Core (5.19.0)
  - SDWebImageAVIFCoder (0.11.0):
    - libavif/core (>= 0.11.0)
    - SDWebImage (~> 5.10)
  - SDWebImagePDFCoder (1.0.1):
    - SDWebImage (>= 5.14.1)
  - SDWebImageSVGCoder (1.7.0):
    - SDWebImage/Core (~> 5.6)
  - SDWebImageSwiftUI (3.0.1):
    - SDWebImage (~> 5.10)
  - SDWebImageWebPCoder (0.14.5):
    - libwebp (~> 1.0)
    - SDWebImage/Core (~> 5.17)

DEPENDENCIES:
  - libavif/libdav1d
  - SDWebImageAVIFCoder
  - SDWebImagePDFCoder
  - SDWebImageSVGCoder
  - SDWebImageSwiftUI (from `./`)
  - SDWebImageWebPCoder

SPEC REPOS:
  trunk:
    - libavif
    - libdav1d
    - libwebp
    - SDWebImage
    - SDWebImageAVIFCoder
    - SDWebImagePDFCoder
    - SDWebImageSVGCoder
    - SDWebImageWebPCoder

EXTERNAL SOURCES:
  SDWebImageSwiftUI:
    :path: "./"

SPEC CHECKSUMS:
  libavif: 84bbb62fb232c3018d6f1bab79beea87e35de7b7
  libdav1d: 23581a4d8ec811ff171ed5e2e05cd27bad64c39f
  libwebp: 1786c9f4ff8a279e4dac1e8f385004d5fc253009
  SDWebImage: 981fd7e860af070920f249fd092420006014c3eb
  SDWebImageAVIFCoder: 00310d246aab3232ce77f1d8f0076f8c4b021d90
  SDWebImagePDFCoder: ec8d162f5a4a34760bf1ea3d7f818dd85dc82e81
  SDWebImageSVGCoder: 15a300a97ec1c8ac958f009c02220ac0402e936c
  SDWebImageSwiftUI: 5acb843d4fb27841adac772aecc0516e9ee90356
  SDWebImageWebPCoder: c94f09adbca681822edad9e532ac752db713eabf

PODFILE CHECKSUM: a1b2837f429f61673bea58532abe00e850c10aeb

COCOAPODS: 1.15.2

```

**Comment by dreampiggy** [comment] 2024-03-29 02:07
I don't think SDWebImageSwifUI `Can not use the latest version of SDWebImage`

**Comment by arbyruns** [comment] 2024-03-30 21:20
@dreampiggy I don't understand your last comment?

I'm getting the following when I upload now. Not sure if it is because of SDWEBImage, but I've added the PrivacyInfo for my app.

ITMS-91053: Missing API declaration - Your app’s code in the “UntitledBarracks” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “UntitledBarracks” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by dreampiggy** [comment] 2024-03-31 04:43
> However, SDWebImageSwiftUI has no way to use the new version, so it's not currently possible to get the required version.

Is your project issue. Maybe your min deployment version is wrong.

The demo shows that "we can always get the new version"

**Comment by dreampiggy** [comment] 2024-04-23 03:53
What linkage did you use ?

For dynamic linkage, each framework use its own symbol. `SDWebImageSwiftUI` does not use any FileSystem API, so it shouldn't

For static linkage, each framework share the same symbol. So maybe you need to declare `NSPrivacyAccessedAPICategoryFileTimestamp` at App level

**Comment by ginnheimerCoder** [comment] 2024-04-23 05:33
We use swift package manager. I don't know wether spm packages are static or dynamic linked. 
SDWebImageSwiftUI has no references to `NSPrivacyAccessedAPICategoryFileTimestamp` but SDWebImage does and SDWebImageSwiftUI depends on it.

**Comment by dreampiggy** [comment] 2024-04-23 06:31
Is that final package actually contains the `Privacy Manifest` ? Maybe the issue is that SDWebImage does not get recognized contains a valid manifest

**Comment by ginnheimerCoder** [comment] 2024-04-23 06:42
<img width="1248" alt="Bildschirmfoto 2024-04-23 um 08 41 22" src="https://github.com/SDWebImage/SDWebImageSwiftUI/assets/49646823/b1cc2b46-2b08-4095-a917-aa7b27058770">

Yes, the privacy manifest file is there, however the reasons for `NSPrivacyAccessedAPICategoryFileTimestamp` don't show up in the privacy report (i just generated one).

**Comment by dreampiggy** [comment] 2024-04-23 07:01
I means, the final package (.ipa)

It seems the syntax is correct as Apple's forum ?

https://github.com/SDWebImage/SDWebImage/blob/master/Package.swift#L35

https://forums.developer.apple.com/forums/thread/742527

**Comment by dreampiggy** [comment] 2024-04-24 01:54
I guess this is SwiftPM only problem, marked as label here. And you can test using CocoaPods or manural archive (using Carthage build for exmaple)

**Comment by ginnheimerCoder** [comment] 2024-04-24 13:55
We don't have CocoaPods nor Carthage in our project, so I am not able to test this easily.

**Comment by arbyruns** [comment] 2024-04-24 14:13
Can you provide what that looks like because I'm still getting warned on this privacy issue using SPM.

**Comment by JoeSzymanskiFAN** [comment] 2024-04-24 14:23
We are using xcodegen, so I'm not 100% sure of how this would look with a standard SPM integration, but we have the following dependencies defined:
```
  SDWebImage:
    # This is a dependency of SDWebImageSwiftUI and SDWebImageSVGCoder, but needs to be
    # explicitly set to v5.19.1 for xcprivacy support. Once those SDKs are updated, we
    # can remove this explicit version tracking.
    url: https://github.com/SDWebImage/SDWebImage
    version: 5.19.1
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    version: 2.2.3
```
This setup makes use of the correct version of SDWebImageSwiftUI, while bumping SDWebImage itself up to the latest version.

**Comment by arbyruns** [comment] 2024-04-24 17:34
Here's what I have 
![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/2520545/10f24f32-8b57-42b2-9c91-6f6458d5c271)

**Comment by JoeSzymanskiFAN** [comment] 2024-04-24 17:46
I'm not sure if there was additional work. We had to have our own privacy manifest set up, so it's possible we resolved our warnings by adding that.

**Comment by arbyruns** [comment] 2024-04-24 17:51
Thanks! I've added mine as well, maybe you have some pointers?

![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/2520545/7ec0527e-e85c-4057-8d19-a74292fd20cf)

**Comment by JoeSzymanskiFAN** [comment] 2024-04-24 17:54
That looks to be about what I would expect. I'm not sure what else would be missing outside of for some reason the file not being included I the final build. Sorry I can't help much more here.

**Comment by ginnheimerCoder** [comment] 2024-04-25 05:43
Adding SDWebImage 5.19.1 via SPM as an explicit dependency to the project does not resolve the issue. I am still getting the privacy issue. 
And SDWebImageSwiftUI already adds SDWebImage 5.19.1, so explicitly adding SDWebImage should not make a difference.

**Comment by dreampiggy** [comment] 2024-04-25 08:41
When using our repo's own Demo (`open SDWebImageSwiftUI.xcworkspace`), click archive, I can see the xcarchive, and the App bundle actually contains the `PrivacyInfo.xcprivacy`, under a bundle named `SDWebImage_SDWebImage.bundle`

![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/6919743/fc205489-33fc-45af-8e62-afeb52cc90d6)


@ginnheimerCoder Does your final app or ipa not contains this file ?

**Comment by ginnheimerCoder** [comment] 2024-04-25 09:06
Using the same tree command, it only shows our own PrivacyInfo file under the root directory of the app. There is no `SDWebImage_SDWebImage.bundle` branch and no PrivacyInfo file in it.

**Comment by ginnheimerCoder** [comment] 2024-04-25 10:09
I re-added SDWebImageSwiftUI and now using the tree command, the `SDWebImage_SDWebImage.bundle`branch is showing up and has the PrivacyInfo file in it – however, Apple is still complaining.

**Comment by dreampiggy** [comment] 2024-04-25 13:22
> however, Apple is still complaining and SDWebImage with the declared reason is not showing up in the privacy report.
So, what's actually needed ? I saw the Apple forum seems some devs use SDWebImage as the correct way.

See: https://forums.developer.apple.com/forums/thread/734971
![image](https://github.com/SDWebImage/SDWebImageSwiftUI/assets/6919743/45dbbc3f-d547-419e-bfff-5091d0afdca9)

**Comment by ginnheimerCoder** [comment] 2024-04-26 05:05
On the Apple forum, nobody mentions the use of SPM.

**Comment by dreampiggy** [comment] 2024-04-26 06:27
> On the Apple forum, nobody mentions the use of SPM. I think this is an SPM issue.

There are no different if you use `Static Library` in CocoaPods.

I guess when you use `.framework` bundle, you will not have any issue. Does the Apple ITC tools only scan for `.framework` (Static framwork or dynamic framework)

**Comment by ginnheimerCoder** [comment] 2024-04-26 06:35
what exactly do you mean when you say "use .framework bundle"? I just included the package via Swift Package Manager. Nothing more. What do I need to change?

**Comment by ginnheimerCoder** [comment] 2024-04-29 07:03
So it seems like the issue has been resolved on the apple side. 
Today I received a response from the TSI i opened. Apple simply said “There has been a change in the policies. You should be able to upload a binary that contains a static framework.”
They linked to [the reminder Apple](https://developer.apple.com/news/?id=pvszzano) released on Friday. 

I uploaded a new build (with no changes to the privacy issue) and up until now I haven’t received the privacy issue e-mail.

**Comment by dreampiggy** [comment] 2024-04-29 08:45
SPM does not use `Static framework` to distribute your code.

It use `Static ar archive`, means, `SDWebImage.a` + `SDWebImage_bundle.bundle`

**Comment by dreampiggy** [comment] 2024-04-29 08:51
If Apple's tool is stupid on `SPM static linking and their dependency`. Maybe the stupid solution we (as developer) is to declare a empty privacy info as well.

**Closed** 2024-04-29 09:00 UTC
Labels: help wanted, swiftpm
